basePath: /api
host: localhost:8080
info:
  contact: {}
  description: Personal Finance API built with Go and Echo.
  title: BudgetCtl API
  version: "1.0"
paths:
  /health:
    get:
      description: Check if the server and database are up
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health Check
      tags:
      - health
  /helloworld:
    get:
      consumes:
      - application/json
      description: get the hello world status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Show Hello World
      tags:
      - intro
swagger: "2.0"
